name: Infracost
description: Run Infracost CI/CD
author: https://github.com/mubeta06
requirements: []
configuration:
  properties:
    pattern:
      type: string
    plan:
      type: string
      default: terraform.tfplan
    version:
      type: string
      default: ci-latest
  additionalProperties: false
