#!/bin/bash
set -euo pipefail

PROJECT="${BUILDKITE_PLUGIN_INFRACOST_PROJECT:=$BUILDKITE_PIPELINE_NAME}"
PLAN="${BUILDKITE_PLUGIN_INFRACOST_PLAN:=plan.json}"

INFRACOST_VERSION="${BUILDKITE_PLUGIN_INFRACOST_VERSION:=ci-latest}"
export INFRACOST_VCS_PROVIDER=$BUILDKITE_PIPELINE_PROVIDER
export INFRACOST_VCS_REPOSITORY_URL=${BUILDKITE_PULL_REQUEST_REPO/.git}
export INFRACOST_VCS_PULL_REQUEST_URL=$INFRACOST_VCS_REPOSITORY_URL/pull/$BUILDKITE_PULL_REQUEST
export INFRACOST_VCS_PULL_REQUEST_AUTHOR=$BUILDKITE_BUILD_AUTHOR

echo "--- Analysing Costs for the :terraform: plan ${PLAN} with ${INFRACOST_VERSION}"

docker run --rm -v $(pwd):/config -w /config \
		-e INFRACOST_API_KEY \
		-e INFRACOST_VCS_PULL_REQUEST_URL \
		-e INFRACOST_VCS_REPOSITORY_URL \
		-e INFRACOST_VCS_PULL_REQUEST_AUTHOR \
		-e INFRACOST_VCS_PULL_REQUEST_TITLE \
		infracost/infracost:$INFRACOST_VERSION \
			diff --project-name $PROJECT --path $PLAN --format json > infracost.json

docker run --rm -v $(pwd):/config -w /config \
		-e INFRACOST_API_KEY \
		-e GITHUB_TOKEN \
		infracost/infracost:$INFRACOST_VERSION \
		comment $INFRACOST_VCS_PROVIDER \
		--path=infracost.json \
		--repo=${INFRACOST_VCS_REPOSITORY_URL#*github.com/*} \
		--github-token=$GITHUB_TOKEN \
		--pull-request=$BUILDKITE_PULL_REQUEST \
		--behavior=update
