#!/bin/bash
set -euo pipefail

PROJECT="$BUILDKITE_PLUGIN_INFRACOST_PROJECT"

PLAN="${BUILDKITE_PLUGIN_INFRACOST_PLAN:=terraform.tfplan}"

INFRACOST_VERSION="${BUILDKITE_PLUGIN_INFRACOST_VERSION:=ci-latest}"

echo "--- :1234: Counting the number of files"

echo "--- Analysing Costs for the :terraform: plan ${PLAN} with ${INFRACOST_VERSION}"

# here we will need to convert the Build environment variables to INFRACOST ones

docker run --rm -v $(pwd):/config -w /config \
		-e INFRACOST_API_KEY \
		-e INFRACOST_VCS_PULL_REQUEST_URL \
		-e INFRACOST_VCS_REPOSITORY_URL \
		-e INFRACOST_VCS_PULL_REQUEST_AUTHOR \
		-e INFRACOST_VCS_PULL_REQUEST_TITLE \
		infracost/infracost:$INFRACOST_VERSION \
			diff --project-name $PROJECT --path $PLAN --format json > infracost.json

COUNT=$(find . -name "$PROJECT" | wc -l)

echo "Found ${COUNT} files matching ${PROJECT}"

buildkite-agent annotate "Found ${COUNT} files matching ${PROJECT}"
